# Generated by Django 5.0.6 on 2024-06-08 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('idkor', models.AutoField(db_column='IdKor', primary_key=True, serialize=False)),
                ('korisnicko_ime', models.CharField(db_column='Korisnicko_ime', max_length=45)),
                ('lozinka', models.CharField(db_column='Lozinka', max_length=45)),
                ('ime', models.CharField(db_column='Ime', max_length=45)),
                ('prezime', models.CharField(db_column='Prezime', max_length=45)),
                ('email', models.CharField(db_column='Email', max_length=45)),
                ('pol', models.CharField(db_column='Pol', max_length=1)),
                ('broj_poena', models.IntegerField(db_column='Broj_poena')),
                ('nivo', models.IntegerField(db_column='Nivo')),
                ('vazeci', models.IntegerField(db_column='Vazeci')),
            ],
            options={
                'db_table': 'korisnik',
            },
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('idkat', models.AutoField(db_column='IdKat', primary_key=True, serialize=False)),
                ('naziv', models.CharField(db_column='Naziv', max_length=45)),
                ('slika', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kategorija',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='EasyQuizzy.korisnik')),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='EasyQuizzy.korisnik')),
            ],
            options={
                'db_table': 'moderator',
            },
        ),
        migrations.CreateModel(
            name='RegistrovaniKorisnik',
            fields=[
                ('idkor', models.OneToOneField(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='EasyQuizzy.korisnik')),
            ],
            options={
                'db_table': 'registrovani_korisnik',
            },
        ),
        migrations.CreateModel(
            name='Pitanje',
            fields=[
                ('idpit', models.AutoField(db_column='IdPit', primary_key=True, serialize=False)),
                ('tekst_pitanja', models.CharField(db_column='Tekst_pitanja', max_length=250, unique=True)),
                ('tezina_pitanja', models.IntegerField(blank=True, db_column='Tezina_pitanja', null=True)),
                ('tacan_odgovor', models.CharField(blank=True, db_column='Tacan_odgovor', max_length=125, null=True)),
                ('netacan1', models.CharField(blank=True, db_column='Netacan1', max_length=125, null=True)),
                ('netacan2', models.CharField(blank=True, db_column='Netacan2', max_length=125, null=True)),
                ('netacan3', models.CharField(blank=True, db_column='Netacan3', max_length=125, null=True)),
                ('zbir_ocena', models.IntegerField(db_column='Zbir_ocena')),
                ('broj_ocena', models.IntegerField(db_column='Broj_ocena')),
                ('prosecna_ocena', models.DecimalField(db_column='Prosecna_ocena', decimal_places=3, max_digits=6)),
                ('status', models.IntegerField(db_column='Status')),
                ('idkat', models.ForeignKey(blank=True, db_column='IdKat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EasyQuizzy.kategorija')),
            ],
            options={
                'db_table': 'pitanje',
            },
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('idoce', models.AutoField(db_column='IdOce', primary_key=True, serialize=False)),
                ('vrednost_ocene', models.IntegerField(db_column='Vrednost_ocene')),
                ('idkor', models.ForeignKey(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, to='EasyQuizzy.korisnik')),
                ('idpit', models.ForeignKey(db_column='IdPit', on_delete=django.db.models.deletion.DO_NOTHING, to='EasyQuizzy.pitanje')),
            ],
            options={
                'db_table': 'ocena',
            },
        ),
    ]
